// <auto-generated />
using System;
using DealerOS.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DealerOS.Api.Infrastructure.Migrations
{
    [DbContext(typeof(DealerOsDbContext))]
    [Migration("20260712215235_VehicleInspection02")]
    partial class VehicleInspection02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DealerOS.Api.Infrastructure.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ActorUserId");

                    b.HasIndex("OrganizationId", "EntityType", "EntityId", "OccurredAt");

                    b.ToTable("events", "audit");
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_users_organization_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserBranchAccess", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "UserId", "BranchId");

                    b.HasIndex("OrganizationId", "BranchId");

                    b.ToTable("user_branch_access", "identity");
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CorrectsInspectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FinalComment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid");

                    b.Property<int>("MileageKm")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_inspections_organization_id");

                    b.HasIndex("OrganizationId", "CorrectsInspectionId");

                    b.HasIndex("OrganizationId", "InspectorId");

                    b.HasIndex("OrganizationId", "TemplateId");

                    b.HasIndex("OrganizationId", "VehicleId")
                        .IsUnique()
                        .HasDatabaseName("ux_inspections_active_vehicle")
                        .HasFilter("\"Status\" IN (1, 2)");

                    b.HasIndex("OrganizationId", "BranchId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_inspections_tenant_branch_status_created");

                    b.ToTable("inspections", "inspections", t =>
                        {
                            t.HasCheckConstraint("ck_inspections_mileage", "\"MileageKm\" BETWEEN 0 AND 3000000");

                            t.HasCheckConstraint("ck_inspections_revision", "\"Revision\" > 0");

                            t.HasCheckConstraint("ck_inspections_status", "\"Status\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_inspections_timestamps", "(\"Status\" = 1 AND \"StartedAt\" IS NULL AND \"CompletedAt\" IS NULL) OR (\"Status\" = 2 AND \"StartedAt\" IS NOT NULL AND \"CompletedAt\" IS NULL) OR (\"Status\" = 3 AND \"StartedAt\" IS NOT NULL AND \"CompletedAt\" IS NOT NULL) OR (\"Status\" = 4 AND \"CompletedAt\" IS NULL)");

                            t.HasCheckConstraint("ck_inspections_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionDefect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("BlocksPublication")
                        .HasColumnType("boolean");

                    b.Property<bool>("BlocksSale")
                        .HasColumnType("boolean");

                    b.Property<bool>("BlocksTestDrive")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<decimal?>("EstimatedRepairAmount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("RepairRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_inspection_defects_organization_id");

                    b.HasIndex("OrganizationId", "CreatedByUserId");

                    b.HasIndex("OrganizationId", "InspectionId", "Severity");

                    b.ToTable("defects", "inspections", t =>
                        {
                            t.HasCheckConstraint("ck_inspection_defects_amount", "\"EstimatedRepairAmount\" IS NULL OR \"EstimatedRepairAmount\" >= 0");

                            t.HasCheckConstraint("ck_inspection_defects_category", "\"Category\" BETWEEN 1 AND 11");

                            t.HasCheckConstraint("ck_inspection_defects_critical", "\"Severity\" <> 3 OR (\"RepairRequired\" AND \"BlocksSale\")");

                            t.HasCheckConstraint("ck_inspection_defects_money", "(\"EstimatedRepairAmount\" IS NULL AND \"Currency\" IS NULL) OR (\"EstimatedRepairAmount\" IS NOT NULL AND \"Currency\" ~ '^[A-Z]{3}$')");

                            t.HasCheckConstraint("ck_inspection_defects_severity", "\"Severity\" IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("InspectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "InspectionId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_inspection_items_snapshot_key");

                    b.ToTable("items", "inspections", t =>
                        {
                            t.HasCheckConstraint("ck_inspection_items_category", "\"Category\" BETWEEN 1 AND 11");

                            t.HasCheckConstraint("ck_inspection_items_result", "\"Result\" IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("ck_inspection_items_sort", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_inspection_photos_object_key");

                    b.HasIndex("OrganizationId", "CreatedByUserId");

                    b.HasIndex("OrganizationId", "DefectId");

                    b.ToTable("photos", "inspections", t =>
                        {
                            t.HasCheckConstraint("ck_inspection_photos_size", "\"SizeBytes\" > 0 AND \"SizeBytes\" <= 8388608");

                            t.HasCheckConstraint("ck_inspection_photos_type", "\"ContentType\" IN ('image/jpeg', 'image/png', 'image/webp')");
                        });
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_inspection_templates_organization_id");

                    b.HasIndex("OrganizationId", "CreatedByUserId");

                    b.HasIndex("OrganizationId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_inspection_templates_organization_version");

                    b.ToTable("templates", "inspections", t =>
                        {
                            t.HasCheckConstraint("ck_inspection_templates_version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "TemplateId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_inspection_template_items_key");

                    b.ToTable("template_items", "inspections", t =>
                        {
                            t.HasCheckConstraint("ck_inspection_template_items_category", "\"Category\" BETWEEN 1 AND 11");

                            t.HasCheckConstraint("ck_inspection_template_items_sort", "\"SortOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("DealerOS.Modules.Organizations.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_branches_organization_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_code");

                    b.ToTable("branches", "organizations");
                });

            modelBuilder.Entity("DealerOS.Modules.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("organizations", "organizations");
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MileageKm")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlannedPurchaseAmount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_vehicles_organization_id");

                    b.HasIndex("OrganizationId", "CreatedByUserId");

                    b.HasIndex("OrganizationId", "StockNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_organization_stock_number");

                    b.HasIndex("OrganizationId", "Vin")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_organization_vin");

                    b.HasIndex("OrganizationId", "BranchId", "CreatedAt")
                        .HasDatabaseName("ix_vehicles_tenant_branch_created");

                    b.ToTable("vehicles", "vehicles", t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_acceptance_state", "(\"Status\" = 1 AND \"AcceptedAt\" IS NULL AND \"StockNumber\" IS NULL) OR (\"Status\" IN (2, 3, 4, 5) AND \"AcceptedAt\" IS NOT NULL AND \"StockNumber\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_vehicles_currency", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_vehicles_mileage", "\"MileageKm\" >= 0 AND \"MileageKm\" <= 3000000");

                            t.HasCheckConstraint("ck_vehicles_purchase_amount", "\"PlannedPurchaseAmount\" > 0");

                            t.HasCheckConstraint("ck_vehicles_status", "\"Status\" IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("ck_vehicles_version", "\"Version\" > 0");

                            t.HasCheckConstraint("ck_vehicles_vin", "\"Vin\" ~ '^[A-HJ-NPR-Z0-9]{17}$'");

                            t.HasCheckConstraint("ck_vehicles_year", "\"Year\" >= 1950 AND \"Year\" <= 9999");
                        });
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.VehicleStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ChangedByUserId");

                    b.HasIndex("OrganizationId", "VehicleId", "ChangedAt");

                    b.ToTable("status_history", "vehicles", t =>
                        {
                            t.HasCheckConstraint("ck_status_history_from", "\"FromStatus\" IS NULL OR \"FromStatus\" IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("ck_status_history_to", "\"ToStatus\" IN (1, 2, 3, 4, 5)");
                        });
                });

            modelBuilder.Entity("DealerOS.Api.Infrastructure.AuditEvent", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserAccount", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserBranchAccess", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Branch", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany("BranchAccess")
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Branch", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Inspections.Domain.Inspection", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CorrectsInspectionId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "InspectorId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Inspections.Domain.InspectionTemplate", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "TemplateId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "VehicleId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionDefect", b =>
                {
                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Inspections.Domain.Inspection", null)
                        .WithMany("Defects")
                        .HasForeignKey("OrganizationId", "InspectionId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionItem", b =>
                {
                    b.HasOne("DealerOS.Modules.Inspections.Domain.Inspection", null)
                        .WithMany("Items")
                        .HasForeignKey("OrganizationId", "InspectionId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionPhoto", b =>
                {
                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Inspections.Domain.InspectionDefect", null)
                        .WithMany("Photos")
                        .HasForeignKey("OrganizationId", "DefectId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionTemplate", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionTemplateItem", b =>
                {
                    b.HasOne("DealerOS.Modules.Inspections.Domain.InspectionTemplate", null)
                        .WithMany("Items")
                        .HasForeignKey("OrganizationId", "TemplateId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Organizations.Branch", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Organizations.Branch", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.VehicleStatusHistory", b =>
                {
                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ChangedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrganizationId", "VehicleId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserAccount", b =>
                {
                    b.Navigation("BranchAccess");
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.Inspection", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionDefect", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("DealerOS.Modules.Inspections.Domain.InspectionTemplate", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
