// <auto-generated />
using System;
using DealerOS.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DealerOS.Api.Infrastructure.Migrations
{
    [DbContext(typeof(DealerOsDbContext))]
    partial class DealerOsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DealerOS.Api.Infrastructure.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ActorUserId");

                    b.HasIndex("OrganizationId", "EntityType", "EntityId", "OccurredAt");

                    b.ToTable("events", "audit");
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_users_organization_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserBranchAccess", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId", "UserId", "BranchId");

                    b.HasIndex("OrganizationId", "BranchId");

                    b.ToTable("user_branch_access", "identity");
                });

            modelBuilder.Entity("DealerOS.Modules.Organizations.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_branches_organization_id");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_branches_organization_code");

                    b.ToTable("branches", "organizations");
                });

            modelBuilder.Entity("DealerOS.Modules.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("organizations", "organizations");
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MileageKm")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PlannedPurchaseAmount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StockNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_vehicles_organization_id");

                    b.HasIndex("OrganizationId", "CreatedByUserId");

                    b.HasIndex("OrganizationId", "StockNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_organization_stock_number");

                    b.HasIndex("OrganizationId", "Vin")
                        .IsUnique()
                        .HasDatabaseName("ux_vehicles_organization_vin");

                    b.HasIndex("OrganizationId", "BranchId", "CreatedAt")
                        .HasDatabaseName("ix_vehicles_tenant_branch_created");

                    b.ToTable("vehicles", "vehicles", t =>
                        {
                            t.HasCheckConstraint("ck_vehicles_acceptance_state", "(\"Status\" = 1 AND \"AcceptedAt\" IS NULL AND \"StockNumber\" IS NULL) OR (\"Status\" = 2 AND \"AcceptedAt\" IS NOT NULL AND \"StockNumber\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_vehicles_currency", "\"Currency\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_vehicles_mileage", "\"MileageKm\" >= 0 AND \"MileageKm\" <= 3000000");

                            t.HasCheckConstraint("ck_vehicles_purchase_amount", "\"PlannedPurchaseAmount\" > 0");

                            t.HasCheckConstraint("ck_vehicles_status", "\"Status\" IN (1, 2)");

                            t.HasCheckConstraint("ck_vehicles_version", "\"Version\" > 0");

                            t.HasCheckConstraint("ck_vehicles_vin", "\"Vin\" ~ '^[A-HJ-NPR-Z0-9]{17}$'");

                            t.HasCheckConstraint("ck_vehicles_year", "\"Year\" >= 1950 AND \"Year\" <= 9999");
                        });
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.VehicleStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "ChangedByUserId");

                    b.HasIndex("OrganizationId", "VehicleId", "ChangedAt");

                    b.ToTable("status_history", "vehicles", t =>
                        {
                            t.HasCheckConstraint("ck_status_history_from", "\"FromStatus\" IS NULL OR \"FromStatus\" IN (1, 2)");

                            t.HasCheckConstraint("ck_status_history_to", "\"ToStatus\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("DealerOS.Api.Infrastructure.AuditEvent", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ActorUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserAccount", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserBranchAccess", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Branch", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany("BranchAccess")
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Organizations.Branch", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.HasOne("DealerOS.Modules.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Organizations.Branch", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "BranchId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "CreatedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.VehicleStatusHistory", b =>
                {
                    b.HasOne("DealerOS.Modules.IdentityAccess.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId", "ChangedByUserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DealerOS.Modules.Vehicles.Domain.Vehicle", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrganizationId", "VehicleId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerOS.Modules.IdentityAccess.UserAccount", b =>
                {
                    b.Navigation("BranchAccess");
                });

            modelBuilder.Entity("DealerOS.Modules.Vehicles.Domain.Vehicle", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
